name: whisper
channels:
  - defaults
dependencies:
  - cudatoolkit
  - cudnn
  - huggingface_hub
  - libgcc-ng
  - ncurses
  - ninja
  - ninja-base
  - numpy
  - numpy-base
  - openssl
  - pip
  - pycparser
  - pyopenssl
  - pysocks
  - pytorch
  - pyyaml
  - readline
  - regex
  - requests
  - setuptools
  - six
  - sqlite
  - tk
  - tokenizers
  - tqdm
  - transformers
  - typing-extensions
  - tzdata
  - urllib3
  - wheel
  - xz
  - yaml
  - zlib